channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.3
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - dagshub==0.6.4
  - matplotlib==3.10.7
  - seaborn==0.13.2
name: mlflow-env

